### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by wolkenschieber** [pinae/ctSESAM-android#1]
When running the app in an Android emulator with API level 27, it crashes after adding a domain. Following exception is thrown:
```
05-24 20:39:54.650 4347-4347/de.pinyto.ctSESAM E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.pinyto.ctSESAM, PID: 4347
    java.lang.RuntimeException: Unable to pause activity {de.pinyto.ctSESAM/de.pinyto.ctSESAM.PasswordSettingsListActivity}: java.lang.IllegalArgumentException: Service not registered: de.pinyto.ctSESAM.SyncServiceEnabledActivity$1@3e84bc0
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3912)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826)
        at android.app.ActivityThread.-wrap15(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalArgumentException: Service not registered: de.pinyto.ctSESAM.SyncServiceEnabledActivity$1@3e84bc0
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1484)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1638)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:703)
        at de.pinyto.ctSESAM.SyncServiceEnabledActivity.onPause(SyncServiceEnabledActivity.java:102)
        at android.app.Activity.performPause(Activity.java:7153)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3901)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878) 
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826) 
        at android.app.ActivityThread.-wrap15(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by pinae** [comment]
Sorry for the late reply. I will try to look into this.

It might help to compile and install the sync-app: https://github.com/pinae/ctSESAMsync-android
