### ISSUE TITLE
App don't work

### ISSUE THREAD

**Issue by jjsarton** [pinae/ctSESAM-android#2]
On a Samsung S8+ with android 8.0 the application don't work and is closed while trying to add a domain.
According to C'T 9 2018 there will be an app Sync-APP which is apparently not on google play.

**Comment by pinae** [comment]
Could you please give some additional information on the error? Android stopped it because of an unhandled exception? It wold help a lot if you could add information with USB-debugging on. Unfortunately you would have to compile the app with Android Studio an the code from this repository.

The sync-app exists but it's design is not really thought through. That's why it is still not in the Play Store. However the code is here: https://github.com/pinae/ctSESAMsync-android

**Comment by bastianraschke** [comment]
The issue actually is:

```
FATAL EXCEPTION: main
Process: de.pinyto.ctSESAM, PID: 27161
java.lang.RuntimeException: Unable to pause activity {de.pinyto.ctSESAM/de.pinyto.ctSESAM.PasswordSettingsListActivity}: java.lang.IllegalArgumentException: Service not registered: de.pinyto.ctSESAM.SyncServiceEnabledActivity$1@ce1822a
    at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4032)
    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3987)
    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3939)
    at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6680)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
 Caused by: java.lang.IllegalArgumentException: Service not registered: de.pinyto.ctSESAM.SyncServiceEnabledActivity$1@ce1822a
    at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1562)
    at android.app.ContextImpl.unbindService(ContextImpl.java:1692)
    at android.content.ContextWrapper.unbindService(ContextWrapper.java:717)
    at de.pinyto.ctSESAM.SyncServiceEnabledActivity.onPause(SyncServiceEnabledActivity.java:103)
    at android.app.Activity.performPause(Activity.java:7337)
    at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1465)
    at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4022)
    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3987) 
    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3939) 
    at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45) 
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809) 
    at android.os.Handler.dispatchMessage(Handler.java:106) 
    at android.os.Looper.loop(Looper.java:193) 
    at android.app.ActivityThread.main(ActivityThread.java:6680) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

and is caused because the still not registered service is tried unregister which cause the exception. An easy fix would be:

```
@Override
public void onPause() {
    if (syncServiceBound) {
        unbindService(syncServiceConnection);
        syncServiceBound = false;
    }
    super.onPause();
}
```
